animations:
 idle:
  name: Parent Christmas Idle
  x: 0
  y: 0
 singUP:
  name: Parent Up Note Dad
  x: -47
  y: 24
 singDOWN:
  name: Parent Down Note Dad
  x: -35
  y: -26
 singLEFT:
  name: Parent Left Note Dad
  x: -30
  y: 19
 singRIGHT:
  name: Parent Right Note Dad
  x: 0
  y: -21
 singUP-alt:
  name: Parent Up Note Mom
  x: -49
  y: 27
 singDOWN-alt:
  name: Parent Down Note Mom
  x: -29
  y: -25
 singLEFT-alt:
  name: Parent Left Note Mom
  x: -29
  y: 17
 singRIGHT-alt:
  name: Parent Right Note Mom
  x: 0
  y: -22
flipX: false